### ISSUE TITLE
Problemas v 2.5.x

### ISSUE THREAD

**Issue by arquio** [AgiliaCenter/Hours-Notification#1]
Buenos días,

he leido que no está testeado para otras versiones de redmine, solo sobre la 2.6.

Hemos hecho la prueba de usarlo y el fallo que obtenemos es que  al cargar algunas horas y superar algún % establecido falla  en el envío del mail ( eso suponemos).

`NameError (uninitialized constant HoursMailer::RBPDF): app/controllers/timelog_controller.rb:110:in`create'`
Gracias.

**Comment by Che931** [comment]
Buenas @arquio ,

Me he instalado redmine 2.5.3 para probar el plugin y me ha salido tu error que es justo al crear el pdf que se envía por mail. 

Me he percatado que el fichero gemfile que contenía la dependencia rbpdf no estaba en el repositorio. Al crearlo e instalarla  el plugin ha funcionado correctamente en esa versión del redmine. He hecho un commit con el fichero en cuestión pero te adjunto su contenido:

``` ruby
source 'https://rubygems.org'
gem "rbpdf", "~> 1.18.6"
```

Un saludo,
Fran Romero

PD: Gracias por probarlo 😄

**Comment by arquio** [comment]
Ulf, acabo de leerte parcheado otro plugin vuestro ;P

Voy a probarlo y os cuento

Un saludo y muchas gracias!

**Comment by arquio** [comment]
Perfecto!
